#!/bin/bash

case_1()
{
	if [ "$1" = "help" ]; then
		echo "This will generate color corrected underwater images. usage: $0 <model_name> <camera_device / ros_image_topic>. For help, type $0 help. "1>&2

	elif [ "$1" = "custom" ]; then
		echo "Enter the choice of pix2pix model (4, 8 or 16 layers):"
		read n_layer
		echo "Enter model name and folder name, or ros image topic:"
		read model_name
		read input
		case_2 $model_name $input $n_layer
	else 
		echo "usage: $0 <model_name> <folder_name/ros_image_topic>. For help, type $0 help. For customization, type $0 custom. "1>&2
	fi

}

case_2()
{
 	model_name=$1
	check_modelname_valid $model_name

 	if [ "$2" = "ugan_image_topic" ]; then
 		image_topic_handler
 	else
 		filename=$2
		check_filename_valid $filename
 	fi
	
	if [ "#$" = 3 ]; then 
		find . -iname 'info_$3.pkl' -exec python eval.py {} $filename \; 
	else 
		find . -iname 'info_4.pkl' -exec python eval.py {} $filename \;
	fi
}

check_modelname_valid()
{

	if [ "$model_name" != "ugan" ]; then
		echo "Only ugan added. Please enter model name correctly"
 		exit 2
	fi

}

check_filename_valid()
{
	if [ ! -d "$dataset"]; then
 		echo "give proper directory"
 		exit 2
 	fi
}

image_topic_handler()
{

	echo "Paste the image_subcriber.py to the scripts in catkin_ws, that subscribes to ugan_image_topic"
	#rosrun image_subcriber.py
	#find . -iname 'info.pkl' -exec python eval.py {} $filename \;

}


case "$#" in

1) case_1 $1
   ;;

2) case_2 $1 $2
   ;;

*) echo "usage: $0 <model_name> <folder_name/ros_image_topic>. For help, type $0 help. For custom mode, type $0 custom" 1>&2
   exit 1
   ;;

esac
